version: "3.8"

networks:
  mgme:

services:
    application:
        build:
          context: ""
          dockerfile: Dockerfile
        env_file:
          - .env
        entrypoint: /entrypoint/entrypoint.sh
        ports:
          - "${APP_PORT}:${APP_PORT}"
        volumes:
          - ./src
          - ./docker/application:/entrypoint
          - ./docker/data:/data
        depends_on:
          - database
        networks:
          - mgme

    database:
        image: "postgres:12"
        ports:
          - "${SQL_PORT}:${SQL_PORT}"
        environment:
          - POSTGRES_USER=${SQL_USER}
          - POSTGRES_PASSWORD=${SQL_PASSWORD}
          - POSTGRES_DATABASE=${SQL_DATABASE}
        volumes:
          - './docker/psql/data:/var/lib/postgresql/data:rw'
          - './docker/application/postgres_initdb.d:/docker-entrypoint-initdb.d'
        command: "-p ${SQL_PORT}"
        networks:
        - mgme
