version: "3.4"

services:
    application:
        build:
          container_name: mgme
          context: .
          dockerfile: Dockerfile
        env_file:
          - .env
        ports:
          - "${APP_PORT}:${APP_PORT}"
        volumes:
          - ./src:/mgme
        depends_on:
          - database

    database:
        container_name: database
        image: "postgres:12"
        ports:
          - "${SQL_PORT}:${SQL_PORT}"
        environment:
          - POSTGRES_USER=${SQL_USER}
          - POSTGRES_PASSWORD=${SQL_PASSWORD}
          - POSTGRES_DATABASE=${SQL_DATABASE}
        volumes:
          - './docker/psql/data:/var/lib/postgresql/data:rw'
        command: "-p ${SQL_PORT}"
