version: "3.9"

services:
    web:
        build:
          context: ""
          dockerfile: Dockerfile
        ports:
          - "5001:5001"
        entrypoint: /entrypoint/entrypoint.sh
        volumes:
        depends_on:
          - mgme-database'
        networks:
          - mgme-network

    mgme-database:
        image: "postgres:12"
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=mgme
        volumes:
          - './docker/psql/data:/var/lib/postgresql/data:rw'
          - './docker/web/postgres_initdb.d:/docker-entrypoint-initdb.d'
        command: "-p 5432"
        networks:
        - mgme-network
