version: "3.4"

services:
    application:
        build:
          context: ""
          dockerfile: Dockerfile
        env_file:
          - .env
        ports:
          - "${APP_PORT}:${APP_PORT}"
        volumes:
          - ./src:/mgme
          - ./docker/data:/data
        depends_on:
          - database

    database:
        image: "postgres:12"
        ports:
          - "${SQL_PORT}:${SQL_PORT}"
        environment:
          - POSTGRES_USER=${SQL_USER}
          - POSTGRES_PASSWORD=${SQL_PASSWORD}
          - POSTGRES_DATABASE=${SQL_DATABASE}
        volumes:
          - './docker/psql/data:/var/lib/postgresql/data:rw'
          - './docker/application/postgres_initdb.d:/docker-entrypoint-initdb.d'
        command: "-p ${SQL_PORT}"
