version: "3.4"

services:
    database:
        image: "postgres:12"
        ports:
          - "${SQL_PORT}:${SQL_PORT}"
        environment:
          - POSTGRES_USER=${SQL_USER}
          - POSTGRES_PASSWORD=${SQL_PASSWORD}
          - POSTGRES_DATABASE=${SQL_DATABASE}
        volumes:
          - './docker/psql/data:/var/lib/postgresql/data:rw'

    api:
      build:
        dockerfile: Dockerfile
        context: ./src/api
      env_file:
        - .env
      environment:
        - "WAIT_HOSTS=${SQL_HOST}:${SQL_PORT}"
        - "WAIT_HOSTS_TIMEOUT=300"
        - "WAIT_SLEEP_INTERVAL=5"
        - "ASPNETCORE_URLS=http://*:${API_PORT}"
      ports:
        - "${API_PORT}:${API_PORT}"
      volumes:
        - ./src/api:/api
      depends_on:
        - database

    client:
      stdin_open: true
      environment:
        - CHOKIDAR_USEPOLLING=true
      build:
        dockerfile: Dockerfile
        context: ./src/client
      volumes:
        - /client/node_modules
        - ./src/client:/client
      depends_on:
        - api

    nginx:
      depends_on:
        - api
        - client
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./src/nginx
      ports:
        - "8080:80"
