// <auto-generated />
using System;
using MGME.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MGME.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210507135230_AddCoreModelsAndRelationsBetweenThem")]
    partial class AddCoreModelsAndRelationsBetweenThem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AdventureNonPlayerCharacter", b =>
                {
                    b.Property<int>("AdventuresId")
                        .HasColumnType("integer");

                    b.Property<int>("NonPlayerCharactersId")
                        .HasColumnType("integer");

                    b.HasKey("AdventuresId", "NonPlayerCharactersId");

                    b.HasIndex("NonPlayerCharactersId");

                    b.ToTable("AdventureNonPlayerCharacter");
                });

            modelBuilder.Entity("AdventurePlayerCharacter", b =>
                {
                    b.Property<int>("AdventuresId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerCharactersId")
                        .HasColumnType("integer");

                    b.HasKey("AdventuresId", "PlayerCharactersId");

                    b.HasIndex("PlayerCharactersId");

                    b.ToTable("AdventurePlayerCharacter");
                });

            modelBuilder.Entity("MGME.Core.Entities.Adventure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ChaosFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 5, 7, 15, 52, 30, 471, DateTimeKind.Local).AddTicks(7040));

                    b.Property<bool>("Resolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Title")
                        .IsUnique();

                    b.ToTable("Adventures");
                });

            modelBuilder.Entity("MGME.Core.Entities.NonPlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int?>("PlayerCharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("NonPlayerCharacters");
                });

            modelBuilder.Entity("MGME.Core.Entities.PlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("MGME.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MGME.Core.Entities.Thread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("AdventureId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int?>("PlayerCharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("PlayerCharacterId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("MGME.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("EmailIsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("GameMaster");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AdventureNonPlayerCharacter", b =>
                {
                    b.HasOne("MGME.Core.Entities.Adventure", null)
                        .WithMany()
                        .HasForeignKey("AdventuresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGME.Core.Entities.NonPlayerCharacter", null)
                        .WithMany()
                        .HasForeignKey("NonPlayerCharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdventurePlayerCharacter", b =>
                {
                    b.HasOne("MGME.Core.Entities.Adventure", null)
                        .WithMany()
                        .HasForeignKey("AdventuresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGME.Core.Entities.PlayerCharacter", null)
                        .WithMany()
                        .HasForeignKey("PlayerCharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MGME.Core.Entities.Adventure", b =>
                {
                    b.HasOne("MGME.Core.Entities.User", "User")
                        .WithMany("Adventures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MGME.Core.Entities.NonPlayerCharacter", b =>
                {
                    b.HasOne("MGME.Core.Entities.PlayerCharacter", "PlayerCharacter")
                        .WithMany("NonPlayerCharacters")
                        .HasForeignKey("PlayerCharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MGME.Core.Entities.User", "User")
                        .WithMany("NonPlayerCharacters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCharacter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MGME.Core.Entities.PlayerCharacter", b =>
                {
                    b.HasOne("MGME.Core.Entities.User", "User")
                        .WithMany("PlayerCharacters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MGME.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("MGME.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MGME.Core.Entities.Thread", b =>
                {
                    b.HasOne("MGME.Core.Entities.Adventure", "Adventure")
                        .WithMany("Threads")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MGME.Core.Entities.PlayerCharacter", "PlayerCharacter")
                        .WithMany("Threads")
                        .HasForeignKey("PlayerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MGME.Core.Entities.User", "User")
                        .WithMany("Threads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adventure");

                    b.Navigation("PlayerCharacter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MGME.Core.Entities.Adventure", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("MGME.Core.Entities.PlayerCharacter", b =>
                {
                    b.Navigation("NonPlayerCharacters");

                    b.Navigation("Threads");
                });

            modelBuilder.Entity("MGME.Core.Entities.User", b =>
                {
                    b.Navigation("Adventures");

                    b.Navigation("NonPlayerCharacters");

                    b.Navigation("PlayerCharacters");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
